/** Navigation Type (Where we are navigating to) */
export enum NavType {
    USER_DETAILS = "user-details",
    MANAGE_USER = "manage-user",
    ACCESS_LOG = "access-log",
    CHANGE_PASSWORD = "change-password",
    OPERATE_HISTORY = "operate-history",
    MANAGE_TASKS = "manage-task",
    REGISTER_PAGE = "register",
    TASK_HISTORY = "task-history",
    USER_APP = "user-app",
    MANAGE_KEYS = "manage-keys",
    MNG_ROLES = "manage-roles",
    MNG_PATHS = "manage-paths",
    MNG_RES = "manage-resources",
    MNG_LOGS = "manage-logs",
    MNG_BOOKMARKS = "manage-bookmarks",

    MANAGE_FILES = "manage-files",
    LOGIN_PAGE = "login-page",
    MANAGE_EXT = "manage-extension",
    FOLDERS = "folders",
    PDF_VIEWER = "pdf-viewer",
    IMAGE_VIEWER = "image-viewer",
    GALLERY = "gallery",
    GALLERY_IMAGE = "gallery-image",
    MEDIA_STREAMER = "media",
    FILE_TASK = "file-task",
    MANAGE_FSGROUP = "manage-fsgroup",
    TXT_VIEWER = "txt-viewer",
}

